# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/upload_trip_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewTripDialog(object):
    def setupUi(self, NewTripDialog):
        NewTripDialog.setObjectName("NewTripDialog")
        NewTripDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        NewTripDialog.resize(1079, 682)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        NewTripDialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(NewTripDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_header = QtWidgets.QLabel(NewTripDialog)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setObjectName("label_header")
        self.gridLayout.addWidget(self.label_header, 0, 0, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewTripDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 1, 1, 2)
        self.label_upload = QtWidgets.QLabel(NewTripDialog)
        self.label_upload.setObjectName("label_upload")
        self.gridLayout.addWidget(self.label_upload, 2, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(NewTripDialog)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(70)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 3)

        self.retranslateUi(NewTripDialog)
        self.buttonBox.accepted.connect(NewTripDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(NewTripDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewTripDialog)

    def retranslateUi(self, NewTripDialog):
        _translate = QtCore.QCoreApplication.translate
        NewTripDialog.setWindowTitle(_translate("NewTripDialog", "Dialog"))
        self.label_header.setText(_translate("NewTripDialog", "Upload Trip"))
        self.label_upload.setText(_translate("NewTripDialog", "Uploading"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("NewTripDialog", "Date"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewTripDialog = QtWidgets.QDialog()
    ui = Ui_NewTripDialog()
    ui.setupUi(NewTripDialog)
    NewTripDialog.show()
    sys.exit(app.exec_())
